export const INITIALIZE_APP_REQUEST = "App/INITIALIZE_APP_REQUEST";
export const INITIALIZE_APP_SUCCESS = "App/INITIALIZE_APP_SUCCESS";
export const INITIALIZE_APP_FAILURE = "App/INITIALIZE_APP_FAILURE";

export const LOAD_INITIAL_REQUEST = "App/LOAD_INITIAL_REQUEST";
export const LOAD_INITIAL_SUCCESS = "App/LOAD_INITIAL_SUCCESS";
export const LOAD_INITIAL_FAILURE = "App/LOAD_INITIAL_FAILURE";